#!/bin/sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
# yabai -m config window_border on
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus
yabai -m config window_placement second_child
# yabai -m config window_topmost               off
yabai -m config window_shadow float
# yabai -m config window_opacity on
# yabai -m config window_opacity_duration 0.0
# yabai -m config active_window_opacity 0.7
# yabai -m config normal_window_opacity 0.87
# yabai -m config window_border                on
# yabai -m config window_border_blur           on
# yabai -m config window_border_width          1
# yabai -m config active_window_border_color   0xffa89984
# yabai -m config normal_window_border_color   0x4432302f
# yabai -m config insert_feedback_color        0xffff0000
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m config layout float
yabai -m config top_padding 3
yabai -m config bottom_padding 4
yabai -m config left_padding 3
yabai -m config right_padding 3
yabai -m config window_gap 6

## Default spaces

# Space 1 Terminal
yabai -m config --space 1 layout bsp
yabai -m rule --add app="Min" space=1

# # Space 2 Research
# yabai -m config --space 2 layout bsp
# yabai -m rule --add app="Google Chrome" space=2
# yabai -m rule --add app="Spotify" space=2
# yabai -m rule --add app="LM Studio" space=2

# Space 3 Web browser
yabai -m config --space 3 layout stack
yabai -m rule --add app="Arc Browser" space=3

# # Space 4 Research Web browser
# yabai -m config --space 4 layout bsp
# yabai -m rule --add app="Notion" space=4
# yabai -m rule --add app="bloop" space=4
# yabai -m rule --add app="Dash" space=4
# yabai -m rule --add app="Obsidian" space=4
# # yabai -m rule --add app="jamovi" space=4
# # yabai -m rule --add app="QGIS" space=4

Space 5 Coding Workspace
yabai -m config --space 5 layout stack
# yabai -m rule --add app="Parallels Desktop" space=5
# yabai -m rule --add app="Hyper" space=5
# yabai -m rule --add app="Iterm" space=5
# yabai -m rule --add app="Notion" opacity=0.95
# yabai -m rule --add app="Calendar" space=5

# Space 6 IDE
yabai -m rule --add app="Cursor" space=6

# yabai -m rule --add app="Microsoft Word"     space=2
# yabai -m rule --add app="Microsoft PowerPoint"     space=2
# yabai -m rule --add app="Microsoft Excel"     space=2
# yabai -m rule --add app="Pages"     space=2
# yabai -m rule --add app="Keynote"     space=2

# yabai -m rule --add app="PDF Expert"     space=3
# yabai -m rule --add app="jamovi"     space=3

# yabai -m rule --add app="Zotero" space=4
# yabai -m rule --add app="Notion" space=4
# yabai -m rule --add app="Calendar" space=4

# yabai -m rule --add app="Spark" space=4
# yabai -m rule --add app="KakaoTalk" space=4

# yabai -m rule --add title="^Emacs Everywhere$" space=^

# ^^ these are annoying
# yabai -m rule --add app="Safari"        space=3
# yabai -m rule --add app="Spotify"       space=4
# yabai -m rule --add app="Discord"       space=5

#Exclusion lists
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Pile$" grid=4:4:1:1:2:2 manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" manage=off
yabai -m rule --add app="^Finder" grid=4:4:1:1:2:2 manage=off
yabai -m rule --add app="^Alfred" manage=off
yabai -m rule --add title="^MiniPlayer$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Numi$" grid=4:4:1:1:2:2 manage=off opactiy=0.3
yabai -m rule --add app="^Mail" manage=off
yabai -m rule --add app="Notes" manage=off
yabai -m rule --add app="Reminder" manage=off
# yabai -m rule --add app="^Finder$" manage=off

# yabai -m config external_bar all:24:0
# yabai -m config external_bar all:0:24

# Always focus on windows in space when chancing space

# https://github.com/koekeishiya/yabai/issues/719
# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
