#!/bin/sh

# Restart yabai
lalt + ctrl + shift - w : yabai --restart-service

# Restart skhd
lalt + ctrl + shift - k : skhd --restart-service

# Yabai Commands

## Focus window

# ctrl - tab : yabai -m space --focus recent
ctrl - 1 : yabai -m space --focus 1
ctrl - 2 : yabai -m space --focus 2
ctrl - 3 : yabai -m space --focus 3
ctrl - 4 : yabai -m space --focus 4
ctrl - 5 : yabai -m space --focus 5
ctrl - 6 : yabai -m space --focus 6
ctrl - 7 : yabai -m space --focus 7
ctrl - 8 : yabai -m space --focus 8
ctrl - 9 : yabai -m space --focus 9
ctrl - 0 : yabai -m space --focus 0
# ctrl - left: yabai -m space --focus prev || yabai -m space --focus last
# ctrl - right: yabai -m space --focus next || yabai -m space --focus first

## Send window and focus

ctrl + rcmd - 1 : yabai -m window --space 1 --focus
ctrl + rcmd - 2 : yabai -m window --space 2 --focus
ctrl + rcmd - 3 : yabai -m window --space 3 --focus
ctrl + rcmd - 4 : yabai -m window --space 4 --focus
ctrl + rcmd - 5 : yabai -m window --space 5 --focus
ctrl + rcmd - 6 : yabai -m window --space 6 --focus
ctrl + rcmd - 7 : yabai -m window --space 7 --focus
ctrl + rcmd - 8 : yabai -m window --space 8 --focus
ctrl + rcmd - 9 : yabai -m window --space 9 --focus
ctrl + rcmd - 0 : yabai -m window --space 0 --focus

## focus window in bsp mode
rcmd - h: yabai -m window --focus west
rcmd - j: yabai -m window --focus south && yabai -m window --focus stack.next
rcmd - k: yabai -m window --focus north && yabai -m window --focus stack.prev
rcmd - l: yabai -m window --focus east

## Swap window in bsp mode
rcmd + ctrl - h: yabai -m window --swap west
rcmd + ctrl - j: yabai -m window --swap south
rcmd + ctrl - k: yabai -m window --swap north
rcmd + ctrl - l: yabai -m window --swap east

## Warp window in bsp mode
rcmd + ctrl + shift - h: yabai -m window --warp west
rcmd + ctrl + shift - j: yabai -m window --warp south
rcmd + ctrl + shift - k: yabai -m window --warp north
rcmd + ctrl + shift - l: yabai -m window --warp east

# rotate tree
rcmd + ctrl - r: yabai -m space --rotate 90

# mirror tree y-axis
rcmd + ctrl - y: yabai -m space --mirror y-axis

# toggle window native fullscreen
shift + rcmd - f : yabai -m window --toggle native-fullscreen

# toggle window fullscreen zoom
rcmd - f : yabai -m window --focus mouse && yabai -m window --toggle zoom-fullscreen
# decrease window size
# rcmd + alt - s : yabai -m window --resize bottom:0:-20
# rcmd + cmd - w : yabai -m window --resize top:0:20

# increase window size
rcmd + alt + shift - h : yabai -m window --resize left:-20:0
rcmd + alt + shift - l : yabai -m window --resize right:-20:0
rcmd + alt + shift - j : yabai -m window --resize top:0:20
rcmd + alt + shift - k : yabai -m window --resize top:0:-20

# move floating window
rcmd + shift - h : yabai -m window --resize left:-50:0 && yabai -m window --resize right:-50:0
rcmd + shift - j : yabai -m window --resize bottom:0:50 && yabai -m window --resize top:0:50
rcmd + shift - k : yabai -m window --resize top:0:-50 && yabai -m window --resize bottom:0:-50
rcmd + shift - l : yabai -m window --resize right:50:0 && yabai -m window --resize left:50:0

# create a new space and follow focus
rcmd + ctrl - n : yabai -m space --create && index="$(yabai -m query --displays --display | jq '.spaces[-1]')" && yabai -m space --focus "${index}"
# create a new space, move window and follow focus
rcmd + shift + ctrl - n : yabai -m space --create && index="$(yabai -m query --displays --display | jq '.spaces[-1]')" && yabai -m window --space "${index}" && yabai -m space --focus "${index}"

rcmd + ctrl - x : yabai -m space --destroy

# close window
rcmd + ctrl - w : yabai -m window --close

## Change layout

rcmd - s: yabai -m space --layout stack
rcmd - d: yabai -m space --layout bsp
rcmd - f: yabai -m space --layout float

## bsp mode balance
rcmd - a: yabai -m space --balance

## Toggle vertical/horizontal split
rcmd - v: yabai -m window --toggle split

# float / unfloat window and center on screen
rcmd - t : yabai -m window --toggle float && yabai -m window --grid 4:4:1:1:2:2

# float / unfloat bigger window and  center on screen
rcmd - z : yabai -m window --toggle float && yabai -m window --grid 4:4:1:1:2:4

# move focused window to occupy the left two thirds of the screen.
rcmd - u : yabai -m window --grid 1:3:0:0:2:1
