#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# parallels shared tool
prlcp &
~/.config/polybar/launch.sh &
# bspc config -set /media/psf/iCloud/pictures/alexander-dudar-district72-shot-1.jpg
# xwallpaper --zoom /media/psf/iCloud/pictures/alexander-dudar-district72-shot-1.jpg
feh --bg-scale /media/psf/Home/Documents/wallpapers/gruvbox/awesome.jpg

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width        1
bspc config top_padding         45
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0
bspc config window_gap          9
bspc config border_radius       10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#928374"
bspc config normal_border_color '#161616'
bspc rule -a firefox desktop='^2'
